stages:
  - build
  - deploy

variables:
  AWS_DEFAULT_REGION: us-east-1
  CI_SHA1: $CI_COMMIT_SHA

image: quay.io/reactiveops/ci-images:v11.2-alpine
services:
  - docker:dind

.aliases:
  - &initialize-dev |
    export ROK8S_CONFIG="deploy/development.config"
    prepare-awscli

  - &initialize-staging |
    export ROK8S_CONFIG="deploy/staging.config"
    prepare-awscli

  - &initialize-prod |
    export ROK8S_CONFIG="deploy/production.config"
    prepare-awscli

build:
  stage: build
  before_script:
    - apk update
    - apk add gradle
    - apk add openjdk11

  script:
    - *initialize-dev
    - ./gradlew api-server:jibDockerBuild
    - docker tag api-server ${ECR_REPOSITORY}:${CI_SHA1}
    - docker push ${ECR_REPOSITORY}:${CI_SHA1}

deploy_staging:
  stage: deploy
  environment:
    name: staging
  script:
    - *initialize-staging
    - helm-deploy -f $ROK8S_CONFIG
  only:
    - /^dev-.*/

deploy_production:
  stage: deploy
  environment:
    name: production
  script:
    - *initialize-prod
    - helm-deploy -f $ROK8S_CONFIG
  only:
    - /^v.*/
  when: manual
