stages:
  - build
  - deploy

variables:
  AWS_DEFAULT_REGION: us-east-1
  CI_SHA1: $CI_COMMIT_SHA

image: quay.io/reactiveops/ci-images:v11.2-alpine
services:
  - docker:dind

build:
  stage: build
  before_script:
    - apk update
    - apk add gradle
    - apk add openjdk11
    - prepare-awscli

  script:
    - ./gradlew api-server:jibDockerBuild
    - docker tag api-server ${ECR_REPOSITORY}:${CI_SHA1}
    - docker push ${ECR_REPOSITORY}:${CI_SHA1}

deploy_staging:
  stage: deploy
  environment:
    name: staging
  variables:
    ROK8S_CONFIG: "deploy/staging.config"
  before_script:
    - sops --kms ${KSM_KEY_ARN} -d -i values/staging.yaml
    - aws eks update-kubeconfig --name ${EKS_CLUSTER}
  script:
    - helm-deploy -f $ROK8S_CONFIG
  only:
    - /^dev-.*/

deploy_production:
  stage: deploy
  environment:
    name: production
  variables:
    ROK8S_CONFIG: "deploy/production.config"
  before_script:
    - sops --kms ${KSM_KEY_ARN} -d -i values/production.yaml
    - aws eks update-kubeconfig --name ${EKS_CLUSTER}
  script:
    - helm-deploy -f $ROK8S_CONFIG
  only:
    - /^v.*/
  when: manual
